### ISSUE TITLE
Items do not post

### ISSUE THREAD

**Issue by Avalanthir** [xyzz/acquisition#379]
Hi,
until yesterday everything was fine.
From then i just cannot post anything on poe.trade.
I make everything in the same way - set price, click refresh and they are not appearing on poe.trade even after few hours.

There are no errors in log, they just don't appear on site.
I'm running the newest version of Acquisition, i even tried to make new forum thread with shop but it did not help aswell.

**Comment by sysbite** [comment]
Same issue here, I expect more people to be affected.
Let's just see what the devs say.

**Comment by xyzz** [comment]
This should be fixed now.

**Comment by Avalanthir** [comment]
it actually didn't . I'm still not becoming online even though i have it enabled in acquisition

**Comment by xyzz** [comment]
Give it an hour - if it still doesn't work we can look into it. Also, you should provide additional information such as your pathofexile.com forum thread.
